baseurl = "https://laco0416.github.io/"
languageCode = "ja-jp"
title = "laco notes"
theme = "beautifulhugo"
googleAnalytics = "UA-52362663-4"

[Params]
  logo = "img/icon.png"
  subtitle = "JavaScript, Web, Angular"

[Author]
  name = "Suguru INATOMI"
  github = "laco0416"
  twitter = "laco0416"
  
[[main.menu]]
  
