baseurl = "http://blog.lacolaco.net/"
languageCode = "ja-JP"
title = "laco's blog"
theme = "beautifulhugo"
googleAnalytics = "UA-52362663-4"

[Params]
  logo = "img/icon.png"
  ogImage = "http://blog.lacolaco.net/img/icon.png"
  subtitle = "JavaScript, Web, Angular"

[Author]
  name = "Suguru INATOMI"
  github = "laco0416"
  twitter = "laco0416"
  
[[menu.main]]
    name = "About"
    weight = -100
    identifier = "about"
    url = "/page/about"
 
[[menu.main]]
    name = "RSS"
    weight = 1
    identifier = "rss"
    url = "/index.xml"
